### ISSUE TITLE
Question about inference command 

### ISSUE THREAD

**Issue by meongeun** [DeepakSridhar/promptsliders#3]
I’m reaching out regarding the inference-promptsliders-sdxl.py script, particularly for adjusting the scale. Could you kindly provide an example of the command or the appropriate settings to run this script?

I attempted the following setup:(b/c i trained the network on smiling)
concept = "smiling"
learned_embed_path = f"outputs/{concept}-promptslider/learned_embeds.safetensors"

However, when I executed the script, I encountered the following error:
Traceback (most recent call last):
  File "/home/codes/slider_manipulation/promptsliders/inference-promptsliders-sdxl.py", line 509, in <module>
    images = pipe(prompt, num_images_per_prompt=1, num_inference_steps=50, generator=generator, start_noise=start_noise, scale=scale, unet=pipe.unet, pipe=pipe).images[0]
  File "/home/anaconda3/envs/pslider/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/codes/slider_manipulation/promptsliders/inference-promptsliders-sdxl.py", line 353, in call
    add_time_ids = self._get_add_time_ids(
  File "/home/anaconda3/envs/pslider/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 710, in _get_add_time_ids
    self.unet.config.addition_time_embed_dim * len(add_time_ids) + text_encoder_projection_dim
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

I would greatly appreciate your guidance on how to resolve this issue and correctly set up the script. Any examples would be incredibly helpful.

**Comment by DeepakSridhar** [comment]
The issue mentioned here is due to the diffusers version mismatch. Please try the diffusers version 0.20.2 and huggingface-hub==0.21 and try running the code.
```
pip install diffusers==0.20.2
pip install huggingface-hub==0.21
```
